import type { Metadata } from "next";
import { Zen_Kaku_Gothic_Antique } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import LayoutWrapper from "./LayoutWrapper";

const zenKakuGothicAntique = Zen_Kaku_Gothic_Antique({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Eres",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={`${zenKakuGothicAntique.className} carlaSans`}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
